import { ArrowRight, ExternalLink, GitCommitHorizontal, SearchCode } from 'lucide-react'
import { Link } from 'react-router-dom'
import PageShell from '../components/PageShell'
import { loadScan } from '../services/storage'

const confidence = n => `${Math.round(n * 100)}%`
export default function Graveyard() {
  const scan = loadScan()
  const fixes = scan?.historicalFixes || []
  return <PageShell className="graveyard-page">
    <section className="graveyard-hero section-wrap"><div className="graveyard-copy"><span className="signal"><span/> HISTORICAL FAILURE INTELLIGENCE</span><h1>The bugs you buried.<br/><em>Kept in sight.</em></h1><p>Likely fixed defects discovered from real recent Git history. Classification is message-based heuristic evidence, never certainty.</p><Link className="button" to="/analyze">Run a new analysis <ArrowRight size={17}/></Link></div><div className="grave-visual"><div className="commit-rail"><i/><i/><i/><i/></div><div className="grave-card back"><small>FIX / HEURISTIC</small><span/></div><div className="grave-card front"><GitCommitHorizontal size={30}/><span className="grave-id">LATEST SCAN</span><h3>{scan ? scan.repository.fullName : 'No repository analyzed'}</h3><p>{scan ? `${fixes.length} likely fixes found across ${scan.recentCommits.length} recent commits.` : 'Run an analysis to populate this archive with real GitHub evidence.'}</p><div className="grave-meta"><span><GitCommitHorizontal/> commits {scan?.recentCommits.length ?? '—'}</span><span>status <b>{scan ? 'scanned' : 'awaiting scan'}</b></span></div></div></div></section>
    <section className="graveyard-empty section-wrap"><div className="empty-rule"><span>GRAVEYARD INDEX</span><i/></div>{!scan ? <><SearchCode size={36}/><h2>The archive is waiting.</h2><p>No repository history has been examined. ForkSight does not display fabricated placeholders.</p></> : <><h2>Likely historical bug-fix commits</h2><p>Evidence from the latest bounded scan. Open any commit to verify it directly on GitHub.</p><div className="grave-index">{fixes.map(fix => <article key={fix.sha}><div className="grave-index-top"><code>{fix.sha.slice(0,7)}</code><span>{new Date(fix.date).toLocaleDateString()}</span><span>{confidence(fix.confidence)} confidence</span></div><h3>{fix.message}</h3><p>Author: {fix.author} · Signals: {fix.signals.join(', ')}</p><div className="path-list">{fix.files.map(file => <code key={file}>{file}</code>)}</div><a href={fix.url} target="_blank" rel="noreferrer">View commit on GitHub <ExternalLink size={13}/></a></article>)}</div>{!fixes.length && <p className="no-findings">No likely bug-fix commit was identified in the latest 30 commits.</p>}</>}<div className="grave-stats"><div><strong>{scan ? fixes.length : '—'}</strong><span>Historical fixes</span></div><div><strong>{scan ? scan.resurrectionRisks.length : '—'}</strong><span>Resurrection matches</span></div><div><strong>{scan ? scan.recentCommits.length : '—'}</strong><span>Commits inspected</span></div></div></section>
  </PageShell>
}
